name: "Main Workflow"


# trigger
on:
  pull_request:
    branches:
      - dev

env:
  Port: 3000

jobs:
  build:
    name: "Build Laravel App"
    runs-on: ubuntu-latest
    steps:

      - name: Setup PHP version 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Git Checkout (Clone data to this action)
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          composer install
          
      - name: "Show Current directory"
        run: |
          pwd
          ls -a

      - name: Setup Env.ci
        run: |
          cp .env.ci .env

      - name: Build the Application
        run: |
          php artisan key:generate


